config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "visitors#index"
  resources :users, only: %i(show)
  resources :timesheets, only: %i(new index create destroy show) do
    resources :tickets, only: %i(create destroy) do
      resource :approved_ticket, only: %i(create)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approved_ticket.rb
class ApprovedTicket < ApplicationRecord
  belongs_to :timesheet
  belongs_to :ticket
  validates :timesheet, presence: true, uniqueness: true
  validates :ticket, presence: true, uniqueness: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :timesheet
  validates :user, presence: true
  validates :timesheet, presence: true
  has_one :approved_ticket
  validate :validate_duplicate_request

  private

  def validate_duplicate_request
    if user.applied_timesheets.where(start_time: timesheet.start_time).any?
      errors.add(:base, "すでに予約申請中です。")
    end
  end
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  belongs_to :user
  has_many :tickets
  has_one :approved_ticket
  validates :start_time, presence: true
  validates :user, presence: true
  validate :validate_past
  validate :validate_start_time
  validate :validate_time_step
  validate :validate_double_book
  scope :order_by_start_time, -> { order(:start_time) }

  TIMES = ["10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00",
           "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30",
           "17:00", "17:30"].freeze

  private

  def validate_past
    if start_time < Time.zone.now
      errors.add(:start_time, ":過去の日付は使用できません。")
    end
  end

  def validate_time_step
    if TIMES.index(start_time.strftime("%H:%M")).nil?
      errors.add(:start_time, ":この時刻では作成できません。")
    end
  end

  def validate_double_book
    timesheet = Timesheet.where(user_id: user_id).where(start_time: start_time)
    if timesheet.any?
      errors.add(:start_time, ":この時間にはすでに予約が作成されています。")
    end
  end

  def validate_start_time
    case start_time.wday
    when 0
      errors.add(:start_time, ":日曜日は作成できません。")
    when 6
      if start_time.hour < 11 || start_time.hour > 15
        errors.add(:start_time, ":土曜日は11:00~15:00のみ作成できます。")
      end
    else
      if start_time.hour < 10 || start_time.hour > 18
        errors.add(:start_time, "平日は10:00~18:00のみ作成できます。")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { user: 0, fp: 1 }
  has_many :timesheets
  has_many :tickets
  has_many :applied_timesheets, through: :tickets, source: 'timesheet'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  add_flash_types :success, :danger

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u|
      u.permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        :remember_me,
        :role
      )
    }
    devise_parameter_sanitizer.permit(:account_update) { |u|
      u.permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        :current_password
      )
    }
  end
end

app/controllers/approved_tickets_controller.rb
class ApprovedTicketsController < ApplicationController
  before_action :set_timesheet_and_ticket
  before_action :permit_only_fp_user!

  def create
    @timesheet.create_approved_ticket!(ticket: @ticket)
    redirect_to current_user, success: "予約を承認しました。"
  rescue ActiveRecord::RecordInvalid => e
    redirect_to timesheet, danger: "予約の承認に失敗しました。#{e.record.errors.join(',')}"
  end

  private

  def set_timesheet_and_ticket
    @timesheet = current_user.timesheets.find(params[:timesheet_id])
    @ticket = @timesheet.tickets.find(params[:ticket_id])
  rescue ActiveRecord::RecordNotFound => e
    redirect_to root_url, danger: "リソースが見つかりませんでした。#{e.record.errors.join(',')}"
  end

  def permit_only_fp_user!
    redirect_to root_url unless current_user.fp?
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    timesheet = Timesheet.find(params[:timesheet_id])
    return unless timesheet.ticket.nil?
    workflow = CreateReservation.new(
      user: current_user, timesheet: timesheet)
    workflow.run
    if workflow.success
      redirect_to current_user
    else
      redirect_to timesheets_path
    end
  end



end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_timesheet, only: %i(create)
  before_action :correct_user, only: %i(destroy)
  before_action :permit_only_normal_user!

  def create
    current_user.tickets.create!(timesheet: @timesheet, message: params[:ticket][:message], charge: params[:ticket][:charge])
    redirect_to current_user, success: "予約に成功しました。"
  rescue ActiveRecord::RecordInvalid => e
    redirect_to timesheets_path, danger: "予約に失敗しました。#{e.record.errors.join(',')}"
  end

  def destroy
    @ticket.destroy!
    redirect_to current_user, success: "予約をキャンセルしました。"
  rescue ActiveRecord::RecordNotDestroyed
    redirect_to root_url, danger: "予約のキャンセルに失敗しました。"
  end

  private

  def set_timesheet
    @timesheet = Timesheet.find(params[:timesheet_id])
  end

  def permit_only_normal_user!
    redirect_to root_url unless current_user.user?
  end

  def correct_user
    @ticket = current_user.tickets.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url, danger: "Ticketが見つかりませんでした。"
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :permit_only_fp_user!, only: %i(new create destroy)
  before_action :set_timesheet, only: %i(destroy show)

  def index
    @timesheets = Timesheet.includes(:user).all.order_by_start_time
  end

  def show
  end

  def new
    @timesheet = current_user.timesheets.build
  end

  def create
    @timesheet = current_user.timesheets.build(timesheet_params)
    if @timesheet.save
      redirect_to timesheets_path, success: "Timesheetを作成しました。"
    else
      render :new
    end
  end

  private

  def timesheet_params
    params.require(:timesheet).permit(:start_time)
  end

  def permit_only_fp_user!
    redirect_to root_url unless current_user.fp?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @timesheets = @user.timesheets.includes(:tickets, :approved_ticket)
    @tickets = @user.tickets.includes(:timesheet)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.slim
- if object.errors.any?
  - object.errors.full_messages.each do |message|
    li = message

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert(class="alert-#{name.to_s == "notice" ? "success" : "danger"}")
      button.close(
        type="button" data-dismiss="alert" aria-hidden="true") &times;
      div(id="flash_#{name}")= msg

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      button.navbar-toggle(
        data-target=".navbar-collapse" data-toggle="collapse")
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    = link_to("FP", root_path, class: "navbar-brand")
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render "layouts/navigation_links"

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  li= link_to(current_user.name, current_user)
  li= link_to("Edit account", edit_user_registration_path)
  li= link_to("Sign out", destroy_user_session_path, method: "delete")
- else
  li= link_to("Sign in", new_user_session_path)
  li= link_to("Sign up", new_user_registration_path)

app/views/layouts/application.html.slim
doctype html
html(lang="en")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yield(:title) : "FP"
    meta(name="description"
      content="#{content_for?(:description) ? yield(:description) : "Globe"}")
    = stylesheet_link_tag("application",
      media: "all", "data-turbolinks-track" => true)
    = javascript_include_tag("application", "data-turbolinks-track" => true)
    = csrf_meta_tags

  body
    header
      = render "layouts/navigation"
    main(role="main")
      .container
        = render "layouts/messages"
        = yield

app/views/timesheets/index.html.slim
h1 All TimeSheets
- @timesheets.each do |timesheet|
  .panel.panel-default
    .container
      h3 開始時刻:#{timesheet.start_time}
      h3 ファイナンシャルプランナー:#{timesheet.user.name}
      - if timesheet.approved_ticket.nil?
        - ticket = timesheet.tickets.build
        = form_for [timesheet, ticket] do |f|
          .form-group
            .row
              .col-xs-9
                = f.text_area :message, placeholder: "メッセージ", class: "form-control"
          .form-group
            .row
              .col-xs-3
                = f.number_field :charge, placeholder: "コンサル料金(円)", class: "form-control"
          .form-group
            .row
              .col-xs-3
                = f.submit "予約する", class: "btn btn-default"
      - else
        h1 満席
      - if current_user == timesheet.user
        = link_to "削除", timesheet, method: :delete

app/views/timesheets/new.html.slim
h1 New TimeSheet
= form_for(@timesheet) do |f|
  = render 'layouts/error_messages', object: @timesheet
  = f.label(:start_time, "start_time")
  = f.datetime_select(:start_time, minute_step: 30,
      start_year: Time.now.year, end_year: Time.now.year + 1)
  = f.submit("Create", class:"btn btn-default")

app/views/timesheets/show.html.slim
- @timesheet.tickets.each do |ticket|
  .panel.panel-default
    .container
      h3 予約者:#{ticket.user.name}
      h3 メッセージ:#{ticket.message}
      h3 コンサル料金:#{ticket.charge}
      - approved_ticket = @timesheet.build_approved_ticket
      = form_for approved_ticket, url: timesheet_ticket_approved_ticket_path(@timesheet, ticket) do |f|
        = f.submit "承認する", class: "btn btn-default"

app/views/users/show.html.slim
h1 = @user.email
h1 = @user.name

- if current_user.fp?
  h1 投稿した予約一覧
  - @timesheets.each do |timesheet|
    .panel.panel-default
      .container
        h3 = timesheet.start_time
        - if timesheet.approved_ticket.nil?
          h3 = timesheet.tickets.size
          = link_to "予約者一覧", timesheet
        - else
          h3 承認済み
- else
  h1 チケット一覧
  - @tickets.each do |ticket|
    .panel.panel-default
      .container
        h3 = ticket.timesheet.start_time
        h3 = ticket.timesheet.user.name
        - if ticket.timesheet.approved_ticket.nil?
          h3 未承認
        - else
          h3 承認済み
        = form_for [ticket.timesheet, ticket], method: :delete do |f|
          = f.submit "キャンセルする", class: "btn btn-default", data: { confirm: "本当にキャンセルしますか？" }

app/views/visitors/index.html.slim
h1 Welcome
#calendar